# docker-compose build jekyll
# docker-compose up
services:
    jekyll:
        image: nkcr/jekyll:v1
        build:
            context: .
        command: jekyll build
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll
